### ISSUE TITLE
Log moving so fast it broke logger module

### ISSUE THREAD

**Issue by anarchy9388** [anarchy9388/scan#11]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 169, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scan_busy_blocks.log.2019-07-10-22-50-57.3' -> '/tmp/scan_busy_blocks.log.2019-07-10-22-50-57.4'
Call stack:
  File "./scan_python3.py", line 1036, in <module>
    scan_busy_blocks_from_disk.main()
  File "./scan_python3.py", line 990, in main
    self.do_scan(chunk_ids, history, is_force)
  File "./scan_python3.py", line 971, in do_scan
    process.start()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./scan_python3.py", line 825, in __do_scan
    end_position))
Message: 'Thread-id-139704112842496 data block length: position: 21635 3756667261 end_position : 3814016800'
Arguments: ()

```

**Comment by MarkHe1222** [comment]
Debug level was enabled for testing, we can disable it when running it.
