### ISSUE TITLE
version 0.8 logging error

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#20]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib64/python3.4/logging/handlers.py", line 115, in rotate
    self.rotator(source, dest)
  File "scan3.py", line 84, in __call__
    os.remove(destination)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scan_busy_blocks_2019-07-17-10-06-42.log.1'
Call stack:
  File "scan3.py", line 549, in <module>
    scan_busy_blocks_from_disk.main()
  File "scan3.py", line 502, in main
    self.do_scan(chunk_ids, history, is_force)
  File "scan3.py", line 485, in do_scan
    receiver_process.start()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "scan3.py", line 414, in receiver
    process.start()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "scan3.py", line 326, in __parse_candidate_block
    multiprocessing.current_process(), data_block_length, position, end_position))
Message: 'Thread-id-<Process(Process-13:45, started)> data block length: 3756107076 position: 5178607506 end_position : 5189747200'
Arguments: ()

**Comment by anarchy9388** [comment]
This is just from the log filling up, it will be a non issue after the script is complete and we disable logging of some operations
