### ISSUE TITLE
issue in zip log rotator

### ISSUE THREAD

**Issue by anarchy9388** [anarchy9388/scan#22]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib64/python3.4/logging/handlers.py", line 115, in rotate
    self.rotator(source, dest)
  File "./scan3.py", line 83, in __call__
    os.remove(destination)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scan_busy_blocks_2019-07-18-20-35-39.log.1'
```

**Comment by anarchy9388** [comment]
Removed zip log rotator for now
