### ISSUE TITLE
please help double check the latest verison script and test it on customer node

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#23]

**Comment by anarchy9388** [comment]
Hit bug on customer site, created #25 for it

**Comment by anarchy9388** [comment]
@MarkHe1222 

Running latest version 0.9 on customer system node 5.
GUI remaining fully functional and the node serving requests without impacting performance.

```

                                 All Requests                                           500 Errors
Node             GETs      PUTs      POSTs     DELETEs  HEADs   Total     GETs    PUTs    POSTs   DELETEs  HEADs   Total
10.142.12.201    2164      4         0         0        0       2168      0       0       0       0        0       0
10.142.12.202    2157      6         0         0        0       2163      0       0       0       0        0       0
10.142.12.203    2158      5         0         0        0       2163      0       0       0       0        0       0
10.142.12.204    2164      4         0         0        0       2168      0       0       0       0        0       0
10.142.12.205    2158      3         0         0        0       2161      0       0       0       0        0       0
10.142.12.206    2157      5         0         0        0       2162      0       0       0       0        0       0
10.142.12.207    2163      3         0         0        0       2166      0       0       0       0        0       0
10.142.12.208    2157      6         0         0        0       2163      0       0       0       0        0       0

Req Totals:      17278     36        0         0        0       17314     0       0       0       0        0       0
Req Error %:                                                              0.00    0.00    0.00    0.00     0.00    0.00

------------------------------------------------------------------------------------------------------------------------
Overall Request Latency (ms)
------------------------------------------------------------------------------------------------------------------------
                             GET                               PUT
Node              Avg        Max        Min       | Avg        Max        Min

10.142.12.201     31.6       289        14          402.0      942        75
10.142.12.202     29.3       273        12          133.3      180        46
10.142.12.203     24.5       199        12          122.8      209        66
10.142.12.204     33.2       299        12          209.2      457        52
10.142.12.205     36.5       457        15          248.3      427        88
10.142.12.206     25.0       223        12          163.4      221        142
10.142.12.207     25.2       209        12          152.3      176        128
10.142.12.208     19.7       140        8           162.0      255        73

Ltcy Overall:     28.1       457        8           199.2      942        46
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
Request Latency Distribution (number of requests in each range)
------------------------------------------------------------------------------------------------------------------------
                             GET            |             PUT            |           DELETE
Node              <1s       1-10s     >10s  |  <1s       1-10s     >10s  |  <1s       1-10s     >10s

10.142.12.201     2164      0         0        4         0         0        0         0         0
10.142.12.202     2157      0         0        6         0         0        0         0         0
10.142.12.203     2158      0         0        5         0         0        0         0         0
10.142.12.204     2164      0         0        4         0         0        0         0         0
10.142.12.205     2158      0         0        3         0         0        0         0         0
10.142.12.206     2157      0         0        5         0         0        0         0         0
10.142.12.207     2163      0         0        3         0         0        0         0         0
10.142.12.208     2157      0         0        6         0         0        0         0         0

Latency Total:    17278     0         0        36        0         0        0         0         0
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
Request Sizes
------------------------------------------------------------------------------------------------------------------------
                               GET                               PUT
Node              Avg (KB)   Max (KB)   Min (KB)    Avg (KB)   Max (KB)   Min (KB)

10.142.12.201     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.202     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.203     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.204     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.205     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.206     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.207     0.3        0.8        0.3         4.0        4.0        4.0
10.142.12.208     0.3        0.8        0.3         4.0        4.0        4.0

Sizes Total:      0.3        0.8        0.3         4.0        4.0        4.0
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
GET Latency Distribution (per request size)
------------------------------------------------------------------------------------------------------------------------
                             <1M                        1-100M                       >100M
Node              <1s       1-10s     >10s  |  <1s       1-10s     >10s  |  <1s       1-10s     >10s

10.142.12.201     2164      0         0        0         0         0        0         0         0
10.142.12.202     2157      0         0        0         0         0        0         0         0
10.142.12.203     2158      0         0        0         0         0        0         0         0
10.142.12.204     2164      0         0        0         0         0        0         0         0
10.142.12.205     2158      0         0        0         0         0        0         0         0
10.142.12.206     2157      0         0        0         0         0        0         0         0
10.142.12.207     2163      0         0        0         0         0        0         0         0
10.142.12.208     2157      0         0        0         0         0        0         0         0

GET Ltcy Total:   17278     0         0        0         0         0        0         0         0
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
PUT Latency Distribution (per request size)
------------------------------------------------------------------------------------------------------------------------
                             <1M                        1-100M                       >100M
Node              <1s       1-10s     >10s  |  <1s       1-10s     >10s  |  <1s       1-10s     >10s

10.142.12.201     4         0         0        0         0         0        0         0         0
10.142.12.202     6         0         0        0         0         0        0         0         0
10.142.12.203     5         0         0        0         0         0        0         0         0
10.142.12.204     4         0         0        0         0         0        0         0         0
10.142.12.205     3         0         0        0         0         0        0         0         0
10.142.12.206     5         0         0        0         0         0        0         0         0
10.142.12.207     3         0         0        0         0         0        0         0         0
10.142.12.208     6         0         0        0         0         0        0         0         0

PUT Ltcy Total:   36        0         0        0         0         0        0         0         0
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
Rate Statistics (per node)
------------------------------------------------------------------------------------------------------------------------
                                   GET                                       PUT
                  MB/s       Avg MB/s   #        # Req in | MB/s       Avg MB/s   #        # Req in
Node              total      per Req    Req/s    parallel | total      per Req    Req/s    parallel

10.142.12.201     0.0        0.0        0.20     0.01       0.0        0.0        0.00     0.00
10.142.12.202     0.0        0.0        0.20     0.01       0.0        0.0        0.00     0.00
10.142.12.203     0.0        0.0        0.20     0.00       0.0        0.0        0.00     0.00
10.142.12.204     0.0        0.0        0.20     0.01       0.0        0.0        0.00     0.00
10.142.12.205     0.0        0.0        0.20     0.01       0.0        0.0        0.00     0.00
10.142.12.206     0.0        0.0        0.20     0.00       0.0        0.0        0.00     0.00
10.142.12.207     0.0        0.0        0.20     0.00       0.0        0.0        0.00     0.00
10.142.12.208     0.0        0.0        0.20     0.00       0.0        0.0        0.00     0.00

Rate Overall:     0.0        0.0        1.60     0.04       0.0        0.0        0.00     0.00
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
GET Extended stats (per request size)
------------------------------------------------------------------------------------------------------------------------
                             <1M                        1-100M                          >100M
                  Avg MB/s  #        # in     | Avg MB/s  #        # in     | Avg MB/s  #        # in
Node              per Req   Req/s    parallel | per Req   Req/s    parallel | per Req   Req/s    parallel

10.142.12.201     0.0       0.20     0.01       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.202     0.0       0.20     0.01       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.203     0.0       0.20     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.204     0.0       0.20     0.01       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.205     0.0       0.20     0.01       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.206     0.0       0.20     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.207     0.0       0.20     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.208     0.0       0.20     0.00       0.0       0.00     0.00       0.0       0.00     0.00

GET Rates:        0.0       1.60     0.04       0.0       0.00     0.00       0.0       0.00     0.00
------------------------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------------------------
PUT Extended stats (per request size)
------------------------------------------------------------------------------------------------------------------------
                             <1M                        1-100M                          >100M
                  Avg MB/s  #        # in     | Avg MB/s  #        # in     | Avg MB/s  #        # in
Node              per Req   Req/s    parallel | per Req   Req/s    parallel | per Req   Req/s    parallel

10.142.12.201     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.202     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.203     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.204     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.205     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.206     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.207     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
10.142.12.208     0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00

PUT Rates:        0.0       0.00     0.00       0.0       0.00     0.00       0.0       0.00     0.00
------------------------------------------------------------------------------------------------------------------------


admin@ecsn5:~> svc_rest_cmd /login
svc_rest_cmd 1.0.10

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<loggedIn>
  <user>emcservice</user>
</loggedIn>
```

**Comment by MarkHe1222** [comment]
@anarchy9388 
Node 8 was down:
```
ecsn8:/tmp #
 0 bash                                                                                                                        ecsn8  08/07 02:42
  File "/tmp/sth/scan.py", line 831, in clean_up_thread
    self.thread.wait(1)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 556, in wait
    self._cond.wait(timeout)
  File "/usr/lib64/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 305, in _exit_function
    _run_finalizers(0)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 506, in _terminate_pool
    worker_handler.join(1e100)
  File "/usr/lib64/python2.7/threading.py", line 951, in join
    self.__block.wait(delay)
  File "/usr/lib64/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 305, in _exit_function
    _run_finalizers(0)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()                                                                                                                                                                              0.11% (262/239339)FREE_BLOCK ETA:99.11hrs
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 506, in _terminate_pool
    worker_handler.join(1e100)
  File "/usr/lib64/python2.7/threading.py", line 951, in join
    self.__block.wait(delay)
  File "/usr/lib64/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
```

**Comment by MarkHe1222** [comment]
From node5.

seem the history output wasn't be flushed as we expect.

```
    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 610975    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611012    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611050    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611090    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611136    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611180    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611232    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611286    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611341    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611397    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611451    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611505    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611558    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611611    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611667    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611723    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611775    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611828    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611879    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 611922    Received: 75    Target Blocks Found: 0    Running Candidate Block ScaTotal parts to pre-check: 2714880    Processed Parts: 61Total parts to preTotal parts to pre-check: 2714880    Processed Parts: 895756    Received: 107    Target Blocks Found: 0    Running Candidate Block Scanner processes:70    Bytes Processed: 68.34 TB

Total parts to pre-check: 2714880    Processed Parts: 896342    Received: 107    Target Blocks Found: 0    Running Candidate Block Scanner processes:70    Bytes Processed: 68.39 TB
```
