### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by MarkHe1222** [anarchy9388/scan#24]
```
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
--- Logging error ---
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib64/python3.4/logging/handlers.py", line 113, in rotate
    os.rename(source, dest)
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib64/python3.4/logging/handlers.py", line 113, in rotate
    os.rename(source, dest)
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 113, in rotate
    os.rename(source, dest)
  File "/usr/lib64/python3.4/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib64/python3.4/logging/handlers.py", line 113, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scan_busy_blocks_2019-07-31-09-21-14.log' -> '/tmp/scan_busy_blocks_2019-07-31-09-21-14.log.1'

```

**Comment by MarkHe1222** [comment]
```
Message: 'Thread-id-<Process(Process-7:47, started)> data block length: 2970611158 position: 1734454975 end_position : 1744828800'
Arguments: ()
  File "/usr/lib64/python3.4/logging/handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/lib64/python3.4/logging/handlers.py", line 113, in rotate
    os.rename(source, dest)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "scan3.py", line 544, in <module>
    scan_busy_blocks_from_disk.main()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "scan3.py", line 482, in main
    self.do_scan(chunk_ids, history, is_force)
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "scan3.py", line 465, in do_scan
    receiver_process.start()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "scan3.py", line 324, in __parse_candidate_block
    multiprocessing.current_process(), data_block_length, position, end_position))
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.4/multiprocessing/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "scan3.py", line 408, in receiver
    process.start()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)

```

**Comment by anarchy9388** [comment]
@MarkHe1222 

Made a custom rotating filehandler for this issue which uses lock.acquire() before rolling over the file and lock.release() after:
```
class CustomRotatingFileHandler(BaseRotatingHandler):
    """
    Handler for logging to a set of files, which switches from one file
    to the next when the current file reaches a certain size.
    """
    def __init__(self, filename, mode='a', maxBytes=0, backupCount=0, encoding=None, delay=False):
        """
        Open the specified file and use it as the stream for logging.

        By default, the file grows indefinitely. You can specify particular
        values of maxBytes and backupCount to allow the file to rollover at
        a predetermined size.

        Rollover occurs whenever the current log file is nearly maxBytes in
        length. If backupCount is >= 1, the system will successively create
        new files with the same pathname as the base file, but with extensions
        ".1", ".2" etc. appended to it. For example, with a backupCount of 5
        and a base file name of "app.log", you would get "app.log",
        "app.log.1", "app.log.2", ... through to "app.log.5". The file being
        written to is always "app.log" - when it gets filled up, it is closed
        and renamed to "app.log.1", and if files "app.log.1", "app.log.2" etc.
        exist, then they are renamed to "app.log.2", "app.log.3" etc.
        respectively.

        If maxBytes is zero, rollover never occurs.
        """
        # If rotation/rollover is wanted, it doesn't make sense to use another
        # mode. If for example 'w' were specified, then if there were multiple
        # runs of the calling application, the logs from previous runs would be
        # lost if the 'w' is respected, because the log file would be truncated
        # on each run.
        if maxBytes > 0:
            mode = 'a'
        BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
        self.maxBytes = maxBytes
        self.backupCount = backupCount

    def doRollover(self):
        """
        Do a rollover, as described in __init__().
        """
        lock.acquire()
        if self.stream:
            self.stream.close()
            self.stream = None
        if self.backupCount > 0:
            for i in range(self.backupCount - 1, 0, -1):
                sfn = self.rotation_filename("%s.%d" % (self.baseFilename, i))
                dfn = self.rotation_filename("%s.%d" % (self.baseFilename,
                                                        i + 1))
                if os.path.exists(sfn):
                    if os.path.exists(dfn):
                        os.remove(dfn)
                    os.rename(sfn, dfn)
            dfn = self.rotation_filename(self.baseFilename + ".1")
            if os.path.exists(dfn):
                os.remove(dfn)
            self.rotate(self.baseFilename, dfn)
        if not self.delay:
            self.stream = self._open()
        lock.release()

    def shouldRollover(self, record):
        """
        Determine if rollover should occur.

        Basically, see if the supplied record would cause the file to exceed
        the size limit we have.
        """
        if self.stream is None:                 # delay was set...
            self.stream = self._open()
        if self.maxBytes > 0:                   # are we rolling over?
            msg = "%s\n" % self.format(record)
            self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
            if self.stream.tell() + len(msg) >= self.maxBytes:
                return 1
        return 0
```

**Comment by anarchy9388** [comment]
@MarkHe1222 
```
15.7.9. Thread Safety
The logging module is intended to be thread-safe without any special work needing to be done by its clients. It achieves this though using threading locks; there is one lock to serialize access to the module’s shared data, and each handler also creates a lock to serialize access to its underlying I/O.

If you are implementing asynchronous signal handlers using the signal module, you may not be able to use logging from within such handlers. This is because lock implementations in the threading module are not always re-entrant, and so cannot be invoked from such signal handlers.
```

We are using asynchronous and logging module file handlers cannot handle it.
Sooo removing the backup count for the file and just logging to one log file with max bytes set to 50gb
